---
version: "3"
services:
 devopsdb:
   image: gopi0810/mynewapp:dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 3

 application:
   image: gopi0810/mynewapp:appimage
   ports:
     - "1234:8080"
   deploy:
     replicas: 3
   depends_on:
     - "devopsdb"
